# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cCx15x-K-qb-bjx8OEYv176-hbIKMcfa
"""

# Aqui fica a função que será usada para cadastrar as notas dos alunos
def cadastrar_notas():
    notas = []
    while True:
        try:
            nota = float(input("Digite a nota do aluno (ou -1 para finalizar): "))

            # Coloquei um break para impedir que o código continue e gere os resultados
            if nota == -1:
                break

            # Aqui estou verificando se existe um intervalo válido para as notas
            if 0 <= nota <= 10:
                notas.append(nota)
            else:
                print("Atenção: A nota deve estar entre 0 e 10")

        except ValueError:
            print("Atenção: Entrada inválida. Digitar apenas números.")

    return notas


# Aqui eu vou colocar uma função para que a média possa ser calculada.
def calcular_media(notas):
    if len(notas) == 0:  # ==0 para evitar divisões por zero
        return 0
    return sum(notas) / len(notas)


# Nas linhas abaixo está uma função com if para poder determinar qual vai ser a situação do aluno
def determinar_situacao(media):
    if media >= 7:
        return "Aprovado!! ✅"
    else:
        return "Reprovado!! ❌"


# Prints no final da função que vou colocar para exibir os relatórios finais da situação total do aluno
def exibir_relatorio(notas, media, situacao):
    print("\n===== RELATÓRIO FINAL =====")
    print(f"Notas inseridas: {notas}")
    print(f"Média: {media:.2f}")
    print(f"Situação: {situacao}")
    print("===========================")


# o programa em si:
def main():
    print("Sistema de Gestão de Notas de Alunos")
    notas = cadastrar_notas()
    media = calcular_media(notas)
    situacao = determinar_situacao(media)
    exibir_relatorio(notas, media, situacao)


# main eentra para execução do programa
main()